object Versions {
    const val coreKtx = "1.12.0"
    const val lifeCycleRuntimeKt = "2.3.1"
    const val activityCompose = "1.3.1"
    const val composeUi = "1.2.0"
    const val junit = "4.13.2"
    const val appCompat = "1.6.1"
    const val material = "1.10.0"
    const val hiltAndroid = "2.44"
    const val hiltAndroidCompiler = "2.44"
    const val hiltCompiler = "2.44"
    const val hiltNavigationCompose = "1.1.0"
    const val retrofit = "2.9.0"
    const val okhttp = "5.5.-alpha.2"
    const val gsonConverter = "2.9.0"
    const val moshi = "1.13.0"
    const val moshiConverter = "2.9.0"
    const val logginInterceptor = "4.8.1"
}